vpn_file_names = [
    'vpn_aim_chat1a.pcap',
    'vpn_aim_chat1b.pcap',
    'vpn_bittorrent.pcap',
    'vpn_email2a.pcap',
    'vpn_email2b.pcap',
    'vpn_facebook_audio2.pcap',
    'vpn_facebook_chat1a.pcap',
    'vpn_facebook_chat1b.pcap',
    'vpn_ftps_A.pcap',
    'vpn_ftps_B.pcap',
    'vpn_hangouts_audio1.pcap',
    'vpn_hangouts_audio2.pcap',
    'vpn_hangouts_chat1a.pcap',
    'vpn_hangouts_chat1b.pcap'
]

nvpn_file_names = [
    'AIMchat1.pcapng',
    'AIMchat2.pcapng',
    'aim_chat_3a.pcap',
    'aim_chat_3b.pcap',
    'email1a.pcap',
    'email1b.pcap',
    'email2a.pcap',
    'email2b.pcap',
    'facebook_audio1a.pcap',
    'facebook_audio1b.pcapng',
    'facebook_audio2a.pcap',
    'facebook_audio2b.pcapng',
    'facebook_audio3.pcapng',
    'facebook_audio4.pcapng',
    'facebookchat1.pcapng',
    'facebookchat2.pcapng',
    'facebookchat3.pcapng',
    'facebook_chat_4a.pcap',
    'facebook_chat_4b.pcap',
    'facebook_video1a.pcap',
    'facebook_video1b.pcapng',
    'facebook_video2a.pcap',
    'facebook_video2b.pcapng',
]

file_name_groups = [
    [
        ('vpn_aim_chat1a.pcap', 'vpn'),
        ('vpn_aim_chat1b.pcap', 'vpn'),
        ('AIMchat1.pcapng', 'nvpn'),
        #('AIMchat2.pcapng', 'nvpn'),
        #('aim_chat_3a.pcap', 'nvpn'),
        #('aim_chat_3b.pcap', 'nvpn'),
    ],
    [
        ('vpn_email2a.pcap', 'vpn'),
        ('vpn_email2b.pcap', 'vpn'),
        ('email2a.pcap', 'nvpn'),
        ('email2b.pcap', 'nvpn'),
    ],
    [
        ('vpn_facebook_audio2.pcap', 'vpn'),
        #('facebook_audio1a.pcap', 'nvpn'),
        ('facebook_audio1b.pcapng', 'nvpn'),
        #('facebook_audio2a.pcap', 'nvpn'),
        ('facebook_audio2b.pcapng', 'nvpn'),
        ('facebook_audio3.pcapng', 'nvpn'),
    ],
    [
        ('vpn_facebook_chat1a.pcap', 'vpn'),
        ('vpn_facebook_chat1b.pcap', 'vpn'),
        ('facebookchat1.pcapng', 'nvpn'),
        ('facebookchat2.pcapng', 'nvpn'),
        ('facebookchat3.pcapng', 'nvpn'),
        ('facebook_chat_4a.pcap', 'nvpn'),
        ('facebook_chat_4b.pcap', 'nvpn'),
    ],
    [
        ('vpn_aim_chat1a.pcap', 'vpn'),
        ('vpn_aim_chat1b.pcap', 'vpn'),
        ('vpn_bittorrent.pcap', 'vpn'),
        ('vpn_email2a.pcap', 'vpn'),
        ('vpn_email2b.pcap', 'vpn'),
        ('vpn_facebook_audio2.pcap', 'vpn'),
        ('vpn_facebook_chat1a.pcap', 'vpn'),
        ('vpn_facebook_chat1b.pcap', 'vpn'),
        ('vpn_ftps_A.pcap', 'vpn'),
        ('vpn_ftps_B.pcap', 'vpn'),
        ('vpn_hangouts_audio1.pcap', 'vpn'),
        ('vpn_hangouts_audio2.pcap', 'vpn'),
        ('vpn_hangouts_chat1a.pcap', 'vpn'),
        ('vpn_hangouts_chat1b.pcap', 'vpn'),
        ('AIMchat1.pcapng', 'nvpn'),
        ('AIMchat2.pcapng', 'nvpn'),
        ('aim_chat_3a.pcap', 'nvpn'),
        ('aim_chat_3b.pcap', 'nvpn'),
        ('email1a.pcap', 'nvpn'),
        ('email1b.pcap', 'nvpn'),
        ('email2a.pcap', 'nvpn'),
        ('email2b.pcap', 'nvpn'),
        ('facebook_audio1a.pcap', 'nvpn'),
        ('facebook_audio1b.pcapng', 'nvpn'),
        ('facebook_audio2a.pcap', 'nvpn'),
        ('facebook_audio2b.pcapng', 'nvpn'),
        ('facebook_audio3.pcapng', 'nvpn'),
        ('facebook_audio4.pcapng', 'nvpn'),
        ('facebookchat1.pcapng', 'nvpn'),
        ('facebookchat2.pcapng', 'nvpn'),
        ('facebookchat3.pcapng', 'nvpn'),
        ('facebook_chat_4a.pcap', 'nvpn'),
        ('facebook_chat_4b.pcap', 'nvpn'),
        ('facebook_video1a.pcap', 'nvpn'),
        ('facebook_video1b.pcapng', 'nvpn'),
        ('facebook_video2a.pcap', 'nvpn'),
        ('facebook_video2b.pcapng', 'nvpn'),
    ]
]