attributes = [
    # "expiration_id",
    "src_ip",
    # "src_mac",
    # "src_oui",
    # "src_port",
    "dst_ip",
    # "dst_mac",
    # "dst_oui",
    # "dst_port",
    # "protocol",
    # "ip_version",
    # "vlan_id",
    # "tunnel_id",
    "bidirectional_mean_piat_ms",
    "src2dst_bytes",
    "src2dst_mean_piat_ms",
    "src2dst_duration_ms",
    "bidirectional_duration_ms",
    "dst2src_duration_ms",
    "dst2src_stddev_piat_ms",
    "dst2src_rst_packets",
    "src2dst_fin_packets",
    "src2dst_syn_packets",
    "bidirectional_fin_packets",
    "dst2src_syn_packets",
    "dst2src_fin_packets",
    "bidirectional_mean_ps",
    "bidirectional_stddev_ps",
    "dst2src_mean_ps",
    # "bidirectional_first_seen_ms",
    # "bidirectional_last_seen_ms",
    # "bidirectional_duration_ms",
    # "bidirectional_packets",
    # "bidirectional_bytes",
    # "src2dst_first_seen_ms",
    # "src2dst_last_seen_ms",
    # "src2dst_duration_ms",
    # "src2dst_packets",
    # "src2dst_bytes",
    # "dst2src_first_seen_ms",
    # "dst2src_last_seen_ms",
    # "dst2src_duration_ms",
    # "dst2src_packets",
    # "dst2src_bytes",
    # "application_name",
    # "application_category_name",
    # "application_is_guessed",
    # "application_confidence",
    # "requested_server_name",
    # "client_fingerprint",
    # "server_fingerprint",
    # "user_agent",
    # "content_type",
]

train_attributes = [
    "bidirectional_mean_piat_ms",
    "src2dst_bytes",
    "src2dst_mean_piat_ms",
    "src2dst_duration_ms",
    "bidirectional_duration_ms",
    "dst2src_duration_ms",
    "dst2src_stddev_piat_ms",
    "dst2src_rst_packets",
    "src2dst_fin_packets",
    "src2dst_syn_packets",
    "bidirectional_fin_packets",
    "dst2src_syn_packets",
    "dst2src_fin_packets",
    "bidirectional_mean_ps",
    "bidirectional_stddev_ps",
    "dst2src_mean_ps",
    "src_freq",
]
